// ONLY SEED DB ONE TIME * UNLESS YOU ARE UPDATING!
/*require('../models/shoes');
require('../models/clothing');
require('../models/accessories');

const mongoose = require('mongoose');
const { Schema } = mongoose;

mongoose.connect('mongodb://heroku_t8scfwmw:16pbj28pfjqevict0d910qto05@ds125058.mlab.com:25058/heroku_t8scfwmw');

var Shoe = mongoose.model('shoe');
var Clothing = mongoose.model('clothing');
var Accessory = mongoose.model('accessory');

shoe = new Shoe({
	productsInfo: {
		bannerImg: '/img/products/shoes/shoes-product1.jpg',
		products: [
			{
				productId: 1,
				typeProduct: 'skateboarding',
				img: '/img/products/shoes/skateboarding/skateboarding1.jpg',
				price: '79.99',
				name: 'Court Graffik SE Shoes',
				color: '8 Colors',
				stars: ['', '', '', '', ''],
				rank: 21,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 2,
				typeProduct: 'skateboarding',
				img: '/img/products/shoes/skateboarding/skateboarding2.jpg',
				price: '90.95',
				name: 'Wes Kremer 2 S Skate',
				color: '7 Colors',
				stars: ['', '', '', '', ''],
				rank: 10,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 3,
				typeProduct:'skateboarding',
				img: '/img/products/shoes/skateboarding/skateboarding3.jpg',
				price: '59.99',
				name: 'Court Kremer 1',
				color: '7 Colors',
				stars: ['', '', '', ''],
				rank: 11,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 4,
				typeProduct: 'skateboarding',
				img: '/img/products/shoes/skateboarding/skateboarding4.jpg',
				price: '85.00',
				name: 'Tiago S Skate Shoes',
				color: '3 Colors',
				stars: ['', '', ''],
				rank: 3,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 5,
				typeProduct: 'skateboarding',
				img: '/img/products/shoes/skateboarding/skateboarding5.jpg',
				price: '70.00',
				name: 'Evan Smith Hi Zero High Top Shoes',
				color: '4 Colors',
				stars: [''],
				rank: 56,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 6,
				typeProduct:'skateboarding',
				img: '/img/products/shoes/skateboarding/skateboarding6.jpg',
				price: '85.00',
				name: 'Hi Zero High Top Shoes little',
				color: '4 Colors',
				stars: ['', '', ''],
				rank: 33,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size'
			},
			{
				productId: 7,
				typeProduct: 'skateboarding',
				img: '/img/products/shoes/skateboarding/skateboarding7.jpg',
				price: '75.00',
				name: 'Wes kramer low',
				color: '8 Colors',
				stars: ['', '', '', ''],
				rank: 9,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 8,
				typeProduct: 'skateboarding',
				img: '/img/products/shoes/skateboarding/skateboarding8.jpg',
				price: '60.00',
				name: 'Evan Smith S Skate Shoes',
				color: '7 Colors',
				stars: ['', '', '', '', ''],
				rank: 2,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 9,
				typeProduct: 'skateboarding',
				img: '/img/products/shoes/skateboarding/skateboarding9.jpg',
				price: '85.00',
				name: 'Evan Smith Hi TX',
				color: '5 Colors',
				stars: ['', '', '', '', ''],
				rank: 1,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 10,
				typeProduct: 'sneakers',
				img: '/img/products/shoes/sneakers/sneakers1.jpg',
				price: '65.00',
				name: 'mens\'s Astor Shoes',
				color: '10 Colors',
				stars: ['', '', '', ''],
				rank: 5,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size'
			},
			{
				productId: 11,
				typeProduct: 'sneakers',
				img: '/img/products/shoes/sneakers/sneakers2.jpg',
				price: '85.00',
				name: 'Heathrow IA Shoes',
				color: '5 Colors',
				stars: ['', '', '', '', ''],
				rank: 1,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 12,
				typeProduct: 'sneakers',
				img: '/img/products/shoes/sneakers/sneakers3.jpg',
				price: '65.00',
				name: 'Astor Shoes Runner',
				color: '10 Colors',
				stars: ['', ''],
				rank: 18,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 13,
				typeProduct: 'sneakers',
				img: '/img/products/shoes/sneakers/sneakers4.jpg',
				price: '45.00',
				name: 'Trase TX Shoes',
				color: '12 Colors',
				stars: ['', '', '', ''],
				rank: 10,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 14,
				typeProduct: 'sneakers',
				img: '/img/products/shoes/sneakers/sneakers5.jpg',
				price: '65.00',
				name: 'Lauran Shoes TX',
				color: '6 Colors',
				stars: ['', '', '', '', ''],
				rank: 23,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 15,
				typeProduct: 'sneakers',
				img: '/img/products/shoes/sneakers/sneakers6.jpg',
				price: '65.00',
				name: 'Phantom Shoes',
				color: '19 Colors',
				stars: ['', '', ''],
				rank: 5,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 16,
				typeProduct: 'sneakers',
				img: '/img/products/shoes/sneakers/sneakers7.jpg',
				price: '80.00',
				name: 'Spartan WC High-Top',
				color: '3 Colors',
				stars: ['', '', '', ''],
				rank: 1,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 17,
				typeProduct: 'sneakers',
				img: '/img/products/shoes/sneakers/sneakers8.jpg',
				price: '75.00',
				name: 'Pure Shoes',
				color: '10 Colors',
				stars: ['', ''],
				rank: 45,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 18,
				typeProduct: 'sandals',
				img: '/img/products/shoes/sandals/sandals1.jpg',
				price: '35.00',
				name: 'mens\'s Recoil Sandals',
				color: '1 Color',
				stars: ['', '', '', '', ''],
				rank: 1,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 19,
				typeProduct: 'boots',
				img: '/img/products/shoes/boots/boots1.jpg',
				price: '110.00',
				name: 'mens\'s Peary Winter Boots',
				color: '1 Colors',
				stars: ['', '', ''],
				rank: 40,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 20,
				typeProduct: 'boots',
				img: '/img/products/shoes/boots/boots2.jpg',
				price: '120.00',
				name: 'Mason Winter Boots',
				color: '3 Colors',
				stars: ['', '', '', ''],
				rank: 13,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 21,
				typeProduct: 'boots',
				img: '/img/products/shoes/boots/boots3.jpg',
				price: '110.00',
				name: 'Doug Winter Boots',
				color: '1 Colors',
				stars: ['', ''],
				rank: 86,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 22,
				typeProduct: 'boots',
				img: '/img/products/shoes/boots/boots4.jpg',
				price: '95.00',
				name: 'Woodland Winter Boots',
				color: '5 Colors',
				stars: ['', '', '', '', ''],
				rank: 6,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 23,
				typeProduct: 'boots',
				img: '/img/products/shoes/boots/boots5.jpg',
				price: '100.00',
				name: 'Heather Winter Boots',
				color: '6 Colors',
				stars: ['', '', '', '', ''],
				rank: 1,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 24,
				typeProduct: 'boots',
				img: '/img/products/shoes/boots/boots6.jpg',
				price: '110.00',
				name: 'Winter Xs Winter Boots',
				color: '2 Colors',
				stars: [''],
				rank: 88,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 25,
				typeProduct: 'boots',
				img: '/img/products/shoes/boots/boots7.jpg',
				price: '110.00',
				name: 'Even Smith Winter Boots',
				color: '2 Colors',
				stars: ['', '', ''],
				rank: 45,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 26,
				typeProduct: 'boots',
				img: '/img/products/shoes/boots/boots8.jpg',
				price: '80.00',
				name: 'TNV Winter Boots',
				color: '1 Color',
				stars: [''],
				rank: 99,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 27,
				typeProduct: 'boots',
				img: '/img/products/shoes/boots/boots9.jpg',
				price: '160.00',
				name: 'High-TopWinter Boots',
				color: '1 Colors',
				stars: ['', ''],
				rank: 65,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 28,
				typeProduct: 'boots',
				img: '/img/products/shoes/boots/boots10.jpg',
				price: '130.00',
				name: 'Uncas Lace Up Winter Boots',
				color: '1 Color',
				stars: [''],
				rank: 97,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 29,
				typeProduct: 'snowboard boots',
				img: '/img/products/shoes/snowboardboots/snowboard1.jpg',
				price: '449.95',
				name: 'Torstein Horgmo BOA',
				color: '1 Color',
				stars: ['', '', '', '', ''],
				rank: 4,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 30,
				typeProduct: 'snowboard boots',
				img: '/img/products/shoes/snowboardboots/snowboard2.jpg',
				price: '300.95',
				name: 'mJudge BOA',
				color: '1 Color',
				stars: ['', '', '', '', ''],
				rank: 3,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 31,
				typeProduct: 'snowboard boots',
				img: '/img/products/shoes/snowboardboots/snowboard3.jpg',
				price: '328.95',
				name: 'Sordda Boggie',
				color: '4 Colors',
				stars: ['', '', '', ''],
				rank: 10,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 32,
				typeProduct: 'snowboard boots',
				img: '/img/products/shoes/snowboardboots/snowboard4.jpg',
				price: '400.95',
				name: 'mens\'s Torstein Horgmo BOA',
				color: '1 Color',
				stars: ['', ''],
				rank: 43,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			},
			{
				productId: 33,
				typeProduct: 'snowboard boots',
				img: '/img/products/shoes/snowboardboots/snowboard5.jpg',
				price: '299.95',
				name: 'Munity Lace Up',
				color: '1 Color',
				stars: ['', '', '', '', ''],
				rank: 8,
				sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10',
						'10.5', '11', '11.5', '12', '12.5', '13', '14'],
				defaultSize: 'Please Select a Size',
				productType: 'shoes'
			}
		]
	}
});

var clothing = new Clothing({
	productsInfo: {
		bannerImg: '/img/products/clothing/clothing-products1.jpg',
		products: [
			{
				productId: 34,
				typeProduct: 'jackets',
				img: '/img/products/clothing/jackets/jacket1.jpg',
				price: '99.99',
				name: 'SPT Workear Jacket',
				color: '1 Color',
				stars: ['', '', '', '', ''],
				rank: 10,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 35,
				typeProduct: 'jackets',
				img: '/img/products/clothing/jackets/jacket2.jpg',
				price: '99.99',
				name: 'Dagup Block Windbreaker',
				color: '1 Color',
				stars: ['', '', '', ''],
				rank: 44,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 36,
				typeProduct: 'jackets',
				img: '/img/products/clothing/jackets/jacket3.jpg',
				price: '79.99',
				name: 'Sk8Mafia Giller',
				color: '1 Color',
				stars: ['', '', '', '', ''],
				rank: 3,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 37,
				typeProduct: 'jackets',
				img: '/img/products/clothing/jackets/jacket4.jpg',
				price: '80.00',
				name: 'Heddon Water',
				color: '2 Colors',
				stars: [''],
				rank: 97,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 38,
				typeProduct: 'jackets',
				img: '/img/products/clothing/jackets/jacket5.jpg',
				price: '149.95',
				name: 'SPT Snow Jacket',
				color: '1 Color',
				stars: ['', '', '', ''],
				rank: 22,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 39,
				typeProduct: 'jackets',
				img: '/img/products/clothing/jackets/jacket6.jpg',
				price: '30.00',
				name: 'Dagup Windbreaker',
				color: '1 Color',
				stars: ['', ''],
				rank: 43,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 40,
				typeProduct: 'jackets',
				img: '/img/products/clothing/jackets/jacket7.jpg',
				price: '100.00',
				name: 'Flux Choaches Jacket',
				color: '8 Colors',
				stars: ['', '', '', '', ''],
				rank: 2,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 41,
				typeProduct: 'jackets',
				img: '/img/products/clothing/jackets/jacket8.jpg',
				price: '45.99',
				name: 'mens\'s Court Graffik SE Shoes',
				color: '5 Colors',
				stars: ['', '', '', ''],
				rank: 17,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 42,
				typeProduct: 'hoodies',
				img: '/img/products/clothing/hoodies/hoodie1.jpg',
				price: '75.00',
				name: 'Start Sherpa Zipper Up',
				color: '4 Colors',
				stars: [''],
				rank: 73,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 43,
				typeProduct: 'hoodies',
				img: '/img/products/clothing/hoodies/hoodie2.jpg',
				price: '42.00',
				name: 'Rebel Raglan Hoddie',
				color: '3 Colors',
				stars: ['', ''],
				rank: 65,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 44,
				typeProduct: 'hoodies',
				img: '/img/products/clothing/hoodies/hoodie3.jpg',
				price: '45.99',
				name: 'mens\'s Court Graffik SE Shoes',
				color: '5 Colors',
				stars: ['', '', '', ''],
				rank: 17,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 45,
				typeProduct: 'hoodies',
				img: '/img/products/clothing/hoodies/hoodie4.jpg',
				price: '50.99',
				name: 'DCxEN',
				color: '1 Colors',
				stars: ['', '', '', ''],
				rank: 36,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 46,
				typeProduct: 'hoodies',
				img: '/img/products/clothing/hoodies/hoodie5.jpg',
				price: '35.00',
				name: 'Rebuilt Hoddie',
				color: '2 Colors',
				stars: ['', '', '', '', ''],
				rank: 7,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes',
			},
			{
				productId: 47,
				typeProduct: 'hoodies',
				img: '/img/products/clothing/hoodies/hoodie6.jpg',
				price: '45.99',
				name: 'mens\'s Court Graffik SE Shoes',
				color: '5 Colors',
				stars: ['', '', '', ''],
				rank: 17,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 48,
				typeProduct: 'hoodies',
				img: '/img/products/clothing/hoodies/hoodie7.jpg',
				price: '37.00',
				name: 'Rebel Block',
				color: '3 Colors',
				stars: ['', '', ''],
				rank: 27,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 49,
				typeProduct: 'hoodies',
				img: '/img/products/clothing/hoodies/hoodie8.jpg',
				price: '45.99',
				name: 'Rep Tile',
				color: '5 Colors',
				stars: ['', '', '', '', ''],
				rank: 8,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 50,
				typeProduct: 'hoodies',
				img: '/img/products/clothing/hoodies/hoodie9.jpg',
				price: '29.99',
				name: 'Phantom 2016',
				color: '5 Colors',
				stars: ['', '', ''],
				rank: 33,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 51,
				typeProduct: 'shirts',
				img: '/img/products/clothing/shirts/shirt1.jpg',
				price: '28.99',
				name: 'Disaster Long Sleeve Tee',
				color: '1 Color',
				stars: ['', '', ''],
				rank: 52,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 52,
				typeProduct: 'shirts',
				img: '/img/products/clothing/shirts/shirt2.jpg',
				price: '20.30',
				name: 'Penstar Long Sleeve Tee',
				color: '2 Colors',
				stars: ['', '', ''],
				rank: 31,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 53,
				typeProduct: 'shirts',
				img: '/img/products/clothing/shirts/shirt3.jpg',
				price: '29.99',
				name: 'DCxEN',
				color: '2 Colors',
				stars: ['', '', '', ''],
				rank: 14,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 54,
				typeProduct: 'shirts',
				img: '/img/products/clothing/shirts/shirt4.jpg',
				price: '29.99',
				name: 'Phantom 2016',
				color: '5 Colors',
				stars: ['', '', ''],
				rank: 33,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 55,
				typeProduct: 'shirts',
				img: '/img/products/clothing/shirts/shirt5.jpg',
				price: '29.99',
				name: 'Rellin Long Sleeve',
				color: '5 Colors',
				stars: ['', '', '', '', ''],
				rank: 3,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 56,
				typeProduct: 'jeans',
				img: '/img/products/clothing/jeans/jeans1.jpg',
				price: '38.99',
				name: 'Rellin Jeans',
				color: '2 Colors',
				stars: ['', '', '', '', ''],
				rank: 9,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 57,
				typeProduct: 'jeans',
				img: '/img/products/clothing/jeans/jeans2.jpg',
				price: '29.99',
				name: 'Sores Jeans',
				color: '5 Colors',
				stars: ['', '', '', '', ''],
				rank: 3,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 58,
				typeProduct: 'jeans',
				img: '/img/products/clothing/jeans/jeans3.jpg',
				price: '42.99',
				name: 'Worker Jeans',
				color: '1 Color',
				stars: ['', '', '', ''],
				rank: 14,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 59,
				typeProduct: 'jeans',
				img: '/img/products/clothing/jeans/jeans4.jpg',
				price: '59.99',
				name: 'Wes Kremer Straight',
				color: '6 Colors',
				stars: ['', '',],
				rank: 57,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 60,
				typeProduct: 'jeans',
				img: '/img/products/clothing/jeans/jeans5.jpg',
				price: '39.99',
				name: 'Rebel Tracksuit',
				color: '5 Colors',
				stars: ['', '', '', '', ''],
				rank: 9,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 61,
				typeProduct: 'jeans',
				img: '/img/products/clothing/jeans/jeans6.jpg',
				price: '29.99',
				name: 'Rellin Long Sleeve',
				color: '3 Colors',
				stars: ['', '', '', '', ''],
				rank: 3,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 62,
				typeProduct: 'shorts',
				img: '/img/products/clothing/shorts/shorts1.jpg',
				price: '27.00',
				name: 'Worker Straight 20.5',
				color: '5 Colors',
				stars: ['', '', '', ''],
				rank: 19,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 63,
				typeProduct: 'shorts',
				img: '/img/products/clothing/shorts/shorts2.jpg',
				price: '27.00',
				name: 'Worker Relaxed',
				color: '5 Colors',
				stars: ['', '', '', '', ''],
				rank: 23,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 64,
				typeProduct: 'shorts',
				img: '/img/products/clothing/shorts/shorts3.jpg',
				price: '48.00',
				name: 'Loose Fit Shorts',
				color: '5 Colors',
				stars: ['', '', ''],
				rank: 29,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			},
			{
				productId: 65,
				typeProduct: 'shorts',
				img: '/img/products/clothing/shorts/shorts4.jpg',
				price: '48.00',
				name: 'Relaxed Fit Shorts',
				color: '5 Colors',
				stars: ['', '', '', ''],
				rank: 35,
				sizes: ['S', 'M', 'L', 'XL', 'XXL'],
				defaultSize: 'Please Select a Size',
				productType: 'clothes'
			}
		]
	}
});

accessory = new Accessory({
	productsInfo: {
		bannerImg: '/img/products/accessories/accessories-products1.jpg',
		products: [
			{
				productId: 66,
				typeProduct: 'hats',
				img: '/img/products/accessories/hats/hats1.jpg',
				price: '21.00',
				name: 'Melties Snapback Hat',
				color: '1 Color',
				stars: ['', '', '', '', ''],
				rank: 1,
				sizes: [],
				defaultSize: 'Size One Size',
				productType: 'accessories'
			},
			{
				productId: 67,
				typeProduct: 'hats',
				img: '/img/products/accessories/hats/hats2.jpg',
				price: '21.99',
				name: 'Flagman',
				color: '1 Color',
				stars: ['', '', '', ''],
				rank: 4,
				sizes: [],
				defaultSize: 'Size One Size',
				productType: 'accessories'
			},
			{
				productId: 68,
				typeProduct: 'hats',
				img: '/img/products/accessories/hats/hats3.jpg',
				price: '19.95',
				name: 'Rikers Hat',
				color: '1 Color',
				stars: ['', '', '', '', ''],
				rank: 21,
				sizes: [],
				defaultSize: 'Size One Size',
				productType: 'accessories'
			},
			{
				productId: 69,
				typeProduct: 'hats',
				img: '/img/products/accessories/hats/hats4.jpg',
				price: '79.99',
				name: 'Finisher Hat',
				color: '1 Color',
				stars: ['', ''],
				rank: 45,
				sizes: [],
				defaultSize: 'Size One Size',
				productType: 'accessories'
			},
			{
				productId: 70,
				typeProduct: 'beanies',
				img: '/img/products/accessories/beanies/beanies1.jpg',
				price: '22.00',
				name: 'Milton Beanie',
				color: '2 Colors',
				stars: ['', '', '', ''],
				rank: 41,
				sizes: [],
				defaultSize: 'Size One Size',
				productType: 'accessories'
			},
			{
				productId: 71,
				typeProduct: 'beanies',
				img: '/img/products/accessories/beanies/beanies2.jpg',
				price: '15.99',
				name: 'HarTanker Beanie',
				color: '4 Colors',
				stars: ['', '', '', '', ''],
				rank: 12,
				sizes: [],
				defaultSize: 'Size One Size',
				productType: 'accessories'
			},
			{
				productId: 72,
				typeProduct: 'beanies',
				img: '/img/products/accessories/beanies/beanies3.jpg',
				price: '15.99',
				name: 'Big Star Beanie',
				color: '1 Color',
				stars: ['', ''],
				rank: 43,
				sizes: [],
				defaultSize: 'Size One Size',
				productType: 'accessories'
			},
			{
				productId: 73,
				typeProduct: 'beanies',
				img: '/img/products/accessories/beanies/beanies4.jpg',
				price: '12.99',
				name: 'Clap Beanie',
				color: '1 Color',
				stars: ['', '', ''],
				rank: 27,
				sizes: [],
				defaultSize: 'Size One Size',
				productType: 'accessories'
			},
			{
				productId: 74,
				typeProduct: 'beanies',
				img: '/img/products/accessories/beanies/beanies5.jpg',
				price: '19.99',
				name: 'Cuff Beanie',
				color: '3 Colors',
				stars: ['', '', '', ''],
				rank: 18,
				sizes: [],
				defaultSize: 'Size One Size',
				productType: 'accessories'
			},
			{
				productId: 75,
				typeProduct: 'bags',
				img: '/img/products/accessories/bags/bag1.jpg',
				price: '40.00',
				name: 'The Breed',
				color: '8 Colors',
				stars: ['', '', '', '', ''],
				rank: 5,
				sizes: [],
				defaultSize: 'Size One Size',
				productType: 'accessories'
			},
			{
				productId: 76,
				typeProduct: 'bags',
				img: '/img/products/accessories/bags/bag2.jpg',
				price: '19.99',
				name: 'Clocked',
				color: '3 Colors',
				stars: ['', '', '', ''],
				rank: 24,
				sizes: [],
				defaultSize: 'Size One Size',
				productType: 'accessories'
			},
			{
				productId: 77,
				typeProduct: 'bags',
				img: '/img/products/accessories/bags/bag3.jpg',
				price: '39.99',
				name: 'Trekker',
				color: '2 Colors',
				stars: [''],
				rank: 60,
				sizes: [],
				defaultSize: 'Size One Size',
				productType: 'accessories'
			},
			{
				productId: 78,
				typeProduct: 'bags',
				img: '/img/products/accessories/bags/bag4.jpg',
				price: '19.99',
				name: 'Cuff Beanie',
				color: '3 Colors',
				stars: ['', '', '', ''],
				rank: 18,
				sizes: [],
				defaultSize: 'Size One Size',
				productType: 'accessories'
			},
			{
				productId: 79,
				typeProduct: 'bags',
				img: '/img/products/accessories/bags/bag5.jpg',
				price: '21.95',
				name: 'Canvas',
				color: '2 Colors',
				stars: ['', '', '', '', ''],
				rank: 2,
				sizes: [],
				defaultSize: 'Size One Size',
				productType: 'accessories'
			}
		]
	}
});


module.exports = {
	seed: function () {
		var instancesOfProducts = [shoe, clothing, accessory];

		instancesOfProducts.map((item) => {	
			item.save().then(() => {
				console.log(`Seed succesful for ${item} products`);
			}).catch((e) => {
				console.log('error: ${item} seed failed ', e);
			});
		});
	}
}
*/


